spring:
  application:
    name: spring-oauth2
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
